TEST = "TEST"

# Database
DBDriver = "mysql"
DBUser = "root"
DBPass = "Vietthptqt10a@"
DBHost="127.0.0.1"
DBPort="3306"
DBName = "buiducviet"

# Redis
RedisHost = "127.0.0.1:6379"
RedisPassword = ""

# Server
SrvHost = "25.20.166.7"
SrvPort = "8080"